### ISSUE TITLE
Add support for Cucumber tags and/or specify a single Scenario in runtime options

### ISSUE THREAD

**Issue by w1150n** [AndrewKeig/protractor-cucumber#13]
We'd like to use Cucumber tags to specify which scenarios are ran. I didn't see anything documented for how to specify a specific tag or how to only run a single scenario by line number. This would really help teams save time by only having to run a specific/failing scenario or scenarios by tag.

**Comment by AndrewKeig** [comment]
This module simply provides some glue between cucumber and protractor, tagging is achieved by adding tags on feature files, as per cucumber.js
