### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by ZolXela** [AndrewKeig/protractor-cucumber#29]
Hello, I have problem with first run example:

I did:
 ~$ cucumber.js ./node_modules/protractor-cucumber/example/features/homepage.feature

I getting:

Feature: Homepage

  As a user
  I want to visit the homepage
  So that I can access the various features on offer

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: callback is not a function
    at new World (/home/aleksandr/node_modules/protractor-cucumber/lib/index.js:35:5)

I installed all tools as described in instruction, step by step before. 

Thanks for soon answer.

**Comment by cajoy** [comment]
It looks like relates to the latest cucumber.js 0.8.0

**Comment by Diodeus** [comment]
I get the same. Just installed today.
