### ISSUE TITLE
Getting 'undefined' error when executing homepage tests

### ISSUE THREAD

**Issue by rahul2983** [AndrewKeig/protractor-cucumber#32]
Hi,

I am getting the following error when i try out the homepage tests after typing cucumber.js

undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )

Can someone help me with this? On a related note how can we force protractor-cucumber package to use a specific version of Selenium Server StandAlone jar ?

Thanks
Rahul Verma

**Comment by tomasz-potanski** [comment]
I experience this issue as well.
Has anybody solved it?

**Comment by xuyukuan** [comment]
I also got the some issue...

**Comment by xuyukuan** [comment]
resolve it!
I got this error when I use node v0.12.4,  it seems it cannot compile selenium-webdriver@2.48.2.

so I update my node version to v4.1.2. now it works perfect.
so you can update you node version, or just downgrade the selenium-webdriver version, hope this can help.

**Comment by rahul2983** [comment]
THanks @tomasz-potanski - Upgrading the Nodejs version worked for me
